-- MySQL Script generated by MySQL Workbench
-- Sat May  9 08:08:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MON_HOC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MON_HOC` (
  `ID_MON_HOC` INT NOT NULL,
  `MonHoc` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_MON_HOC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PHAN_QUYEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PHAN_QUYEN` (
  `ID_PHAN_QUYEN` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PHAN_QUYEN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SINH_VIEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SINH_VIEN` (
  `ID_SINH_VIEN` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `PHAN_QUYEN_ID_PHAN_QUYEN` INT NOT NULL,
  PRIMARY KEY (`ID_SINH_VIEN`),
  CONSTRAINT `fk_SINH_VIEN_PHAN_QUYEN1`
    FOREIGN KEY (`PHAN_QUYEN_ID_PHAN_QUYEN`)
    REFERENCES `mydb`.`PHAN_QUYEN` (`ID_PHAN_QUYEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DIEM` (
  `Diem` DOUBLE NOT NULL,
  `SINH_VIEN_ID_SV` INT NOT NULL,
  `MON_HOC_ID_MON_HOC` INT NOT NULL,
  CONSTRAINT `fk_DIEM_SINH_VIEN`
    FOREIGN KEY (`SINH_VIEN_ID_SV`)
    REFERENCES `mydb`.`SINH_VIEN` (`ID_SINH_VIEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DIEM_MON_HOC1`
    FOREIGN KEY (`MON_HOC_ID_MON_HOC`)
    REFERENCES `mydb`.`MON_HOC` (`ID_MON_HOC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GIAO_VIEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GIAO_VIEN` (
  `ID_GIAO_VIEN` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `PHAN_QUYEN_ID_PHAN_QUYEN` INT NOT NULL,
  PRIMARY KEY (`ID_GIAO_VIEN`),
  CONSTRAINT `fk_GIAO_VIEN_PHAN_QUYEN1`
    FOREIGN KEY (`PHAN_QUYEN_ID_PHAN_QUYEN`)
    REFERENCES `mydb`.`PHAN_QUYEN` (`ID_PHAN_QUYEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
